# Generated by Django 5.2.6 on 2025-09-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='wachers_count',
            new_name='watchers_count',
        ),
    ]
